version: "3.3"
services:
  dict:
    container_name: dict
    image: czap/dict:develop
    build:
      dockerfile: ./Dockerfile
      context: .
      args:
        - CORE_TAG=develop
    environment:
      - PROFILES=dockerlocal
    ports:
      - 8091:8091

networks:
  default:
    external:
      name: czap
