package com.zap.contadigital.comprovantes.enums;

public enum ConfiguracaoTemplate {
    CONTAZAP_QRCODE_ESTATICO,
    COMPROVANTE_RECARGA_CELULAR,
    COMPROVANTE_PAGAMENTO,
    COMPROVANTE_P2P,
    COMPROVANTE_MESMA_TITULARIDADE,
    COMPROVANTE_OUTRA_TITULARIDADE
}
