## Configuração Local (Máquina do Desenvolvedor) ##

server:
  host: localhost

eureka:
  host: localhost
  port: 8081
  name: eureka

database:
  host: contazap-hml-db02.crasuwtpbtmk.us-east-1.rds.amazonaws.com
  port: 5432
  name: zap_webservices
  username: contazaphm
  password: JFJSgqq2LYmjQGp1KMG

endpoint:
  matera-server: https://contazap-mp-api-hmg.matera.com
  matera-edge: https://contazap-mp-edge-hmg.matera.com

encrypt:
  api-access-key: 5459FAE2-6BFD-4E24-AA5D-FD1C084AF80C
  secret-Key: 959A8596-752F-4771-9BD9-642C68B906A9

logging:
  level:
    root: INFO
    com.zap.contadigital: TRACE
    com.sample.feign.demofeigncustomconfig: INFO
    org.springframework.web.client: INFO
    org.springframework.security.oauth2: INFO
